#!/bin/sh

"$AMSBIN/ams" << eor

Task SinglePoint
System
    Atoms
        O -0.0 0.272222 0.0 
        H 0.0 0.863889 0.759139 
        H -0.0 0.863889 -0.759139 
    End
    BondOrders
         1 2 1.0
         1 3 1.0
    End
End

Engine ADF
    Basis
        Type TZ2P
        Core None
    End
    XC
        Hybrid PBE0
        DISPERSION Grimme3 BJDAMP
    End
    Relativity
        Level Spin-Orbit
        Formalism X2C
        SpinOrbitMagnetization NonCollinear
    End
    NumericalQuality Good
EndEngine
eor

